chore: Format, Lint, ビルドテストをするCIパイプラインを整備
ricora/order pull request #14
Opened 2024-08-27 01:43 UTC by r4ai

2024-08-27 10:34 UTC, 3w36zj6 requested changes

2024-08-27 10:34 UTC, 3w36zj6 commented on .github/workflows/ci.yml
> +        run: bun run check
`biome check`の他に`biome ci`という非常に似たコマンドがありますが、後者のほうがCI環境に特化した機能があるので、こちらを利用したほうが良いかもしれません。

https://biomejs.dev/blog/biome-v1-5/#the-command-biome-ci-now-prints-diagnostics-in-github-prs

2024-08-27 10:40 UTC, r4ai commented on .github/workflows/ci.yml
> +        run: bun run check
https://github.com/ricora/order/pull/14/commits/79766cf52581d7b143a469862606f3d1530b1d14 にて修正しました

2024-08-27 10:45 UTC, 3w36zj6 requested changes

2024-08-27 10:45 UTC, 3w36zj6 commented on .github/workflows/ci.yml
> +      - name: Lint and format with Biome
NITS: import sortingが行われていることも明示したほうが良いかもしれません。suggestionは公式ドキュメントの表現を参考にしました。

https://biomejs.dev/ja/reference/cli/#biome-ci

```suggestion
      - name: Run formatter, linter and import sorting with Biome
```

2024-08-27 10:48 UTC, 3w36zj6 approved these changes

2024-09-05 13:12 UTC, sou1118 approved these changes

2024-09-05 13:27 UTC, merged