厨房画面の自動読み込みを導入
ricora/order pull request #18
Opened 2024-10-20 13:18 UTC by BruCandy

厨房画面で自動的にデータを読み込み、新しく入った注文を自動的に表示できるようにしました。

2024-10-21 07:36 UTC, r4ai requested changes

2024-10-21 07:36 UTC, r4ai commented on app/hooks/useKitchenRefresh.ts
ファイル名とカスタムフックの名前が一致していないので、ファイル名を`useKitchenData`に変更すると良いと思います！

2024-10-21 07:59 UTC, BruCandy commented on app/hooks/useKitchenRefresh.ts
変更しました。

2024-10-21 08:00 UTC, r4ai approved these changes

2024-10-22 00:45 UTC, 3w36zj6 approved these changes

2024-10-22 00:48 UTC, merged