簡易レジの作成
ricora/order pull request #26
Opened 2024-11-08 09:33 UTC by BruCandy

## 簡易レジを作成しました。以下の機能が付いています。

- 足し算、引き算、掛け算
- 「C」ボタンで計算の初期化
- 「T」ボタンで注文商品の合計金額を出せる。ただし、二つ目の数字を入れるときに限る。

2024-11-11 05:53 UTC, 3w36zj6 requested changes
MUST: UIとロジックを分離してください。

2024-11-11 06:26 UTC, r4ai commented
簡易レジのロジックは #31 で実装するので、本PRに含まれるロジック部分は削除してください

2024-11-14 10:15 UTC, r4ai approved these changes

2024-11-16 11:19 UTC, 3w36zj6 approved these changes

2024-11-16 16:17 UTC, merged