大体やった
ricora/order pull request #5
Opened 2024-10-10 09:34 UTC by BruCandy

2024-10-10 16:30 UTC, r4ai approved these changes
LGTM!

2024-10-10 16:36 UTC, r4ai commented
@BruCandy 

#4 にてPrettierを導入して自動フォーマットをかけた関係で、一部コンフリクトが発生しているので、コンフリクト解消お願いします！
競合している箇所は、mainブランチの内容を無視して、このブランチの内容で上書きすると良いと思います！

bun.lockbに関しては、package.jsonのコンフリクトを解決した後に、`bun install`を実行してbun.lockbを再生成すると良いと思います

2024-10-10 23:44 UTC, BruCandy commented
vscode上でgitignoreにprisma/dev.dbを追加し、MenuIconButton.tsxの内容も簡潔に直したのですが、コンフリクトについてがよくわからないです。本来はコンフリクトが起きていたら、vscode上で以下のようになりますか？
<<<<<<< HEAD

=======

>>>>>>>

2024-10-12 05:42 UTC, 3w36zj6 requested changes

2024-10-12 05:42 UTC, 3w36zj6 commented on package.json
> +    "prisma": "^5.20.0",
MUST: Prettierが意図せず削除されてしまっているので修正してください。

2024-10-12 12:18 UTC, 3w36zj6 requested changes

2024-10-12 12:18 UTC, 3w36zj6 commented on app/components/molecules/MenueDrawer.tsx
MUST: 意図しているファイル名は`MenuDrawer.tsx`だと思いますので、修正してください。

2024-10-15 02:03 UTC, BruCandy commented on app/components/molecules/MenueDrawer.tsx
変更します。反応が遅くなりすみませんでした。

2024-10-16 12:59 UTC, 3w36zj6 approved these changes

2024-10-17 09:17 UTC, merged